name: flutter_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cloud_firestore: ^3.1.18
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^3.0.1
  google_fonts: ^3.0.1
  hive: ^2.0.5
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  stream_transform: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  google_sign_in: ^5.4.0
  provider: ^6.0.3

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bitmap/
    - assets/images/flags/
    - assets/images/illustration/
    - assets/images/icons/
    - assets/fonts/

  fonts:
    - family: Jost
      fonts: 
      
      - asset: assets/fonts/Jost-Bold.ttf
        
        weight: 700
      - asset: assets/fonts/Jost-BoldItalic.ttf
        
        weight: 700
      - asset: assets/fonts/Jost-ExtraBold.ttf
        
        weight: 800
      - asset: assets/fonts/Jost-ExtraBoldItalic.ttf
        
        weight: 800
      - asset: assets/fonts/Jost-ExtraLight.ttf
        
        weight: 200
      - asset: assets/fonts/Jost-ExtraLightItalic.ttf
        
        weight: 200
      - asset: assets/fonts/Jost-Italic.ttf
        
        weight: 400
      - asset: assets/fonts/Jost-Medium.ttf
        
        weight: 500
      - asset: assets/fonts/Jost-MediumItalic.ttf
        
        weight: 500
      - asset: assets/fonts/Jost-Regular.ttf
        
        weight: 400
      - asset: assets/fonts/Jost-SemiBold.ttf
        
        weight: 600
      - asset: assets/fonts/Jost-SemiBoldItalic.ttf
        
        weight: 600
      - asset: assets/fonts/Jost-Thin.ttf
        
        weight: 100
      - asset: assets/fonts/Jost-ThinItalic.ttf
        
        weight: 100
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter-Black.ttf
        
        weight: 900
      - asset: assets/fonts/Inter-Bold.ttf
        
        weight: 700
      - asset: assets/fonts/Inter-ExtraBold.ttf
        
        weight: 800
      - asset: assets/fonts/Inter-ExtraLight.ttf
        
        weight: 200
      - asset: assets/fonts/Inter-Regular.ttf
        
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        
        weight: 500
      - asset: assets/fonts/Inter-Light.ttf
        
        weight: 300
      - asset: assets/fonts/Inter-SemiBold.ttf
        
        weight: 600
      - asset: assets/fonts/Inter-Thin.ttf
        
        weight: 100
