// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB6VKS0npZxb7gE093TQUs-AjxAY7NFSI',
    appId: '1:95105668432:web:e8f2f1f9ce6dfbb7828855',
    messagingSenderId: '95105668432',
    projectId: 'airplane-app-97253',
    authDomain: 'airplane-app-97253.firebaseapp.com',
    storageBucket: 'airplane-app-97253.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiunk5D1X8-6dh94HxLVNyRUDxQObMNyQ',
    appId: '1:95105668432:android:bb9bb33194baff92828855',
    messagingSenderId: '95105668432',
    projectId: 'airplane-app-97253',
    storageBucket: 'airplane-app-97253.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrP_qBfGB9QgRhfZwuUhh9u-u51Pgzlaw',
    appId: '1:95105668432:ios:c689f96b87dcb8cc828855',
    messagingSenderId: '95105668432',
    projectId: 'airplane-app-97253',
    storageBucket: 'airplane-app-97253.appspot.com',
    iosClientId: '95105668432-1j4fpcnts18i1mskcudk79eoh7jsinhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplaneBookingApp',
  );
}
